if (con == 0 && obj_mainchara.x >= x && global.interact == 0)
{
    con = 1
    global.interact = 1
}
if (con == 1)
{
con = 2
cutscene_master = scr_cutscene_make()
scr_maincharacters_actors()
scr_cutscene_loaded()
ra = 2
    ra_actor = instance_create(1079, 640, obj_actor)
    scr_actor_setup(ra, ra_actor, "ralsei")
	c_sel(ra)
	ra_actor.sprite_index = spr_ralsei_act
	c_sel(ra)
	c_sprite(spr_ralsei_spin)
	c_animate(1, 10, 0.5)
c_sel(su)
c_speaker("susie")
c_msgsetloc(0, "\\E1* Kris^1, this place is weird./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Probably weirder than anything that came before it./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Maybe that's because we're UNDER. THE. GODDAMN. WATER./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Strangely, I don't feel like we're actually under water though./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Which is good, I guess./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_sel(ra)
c_walkdirect(1079, 330, 75)
c_sprite(spr_ralsei_spin)
c_animate(1, 10, 0.5)
c_wait(40)
c_speaker("ralsei")
c_msgsetloc(0, "\\EH* Kris, Susie!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_sel(su)
c_facing("l")
c_sel(kr)
c_facing("l")
c_sel(ra)
c_facing("l")
c_speaker("susie")
c_msgsetloc(0, "\\E7* Ralsei! Where the hell were you?!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E7* You missed an entire adventure!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\EH* Oh, I was just out doing other things!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\EH* Besides, I knew you and Kris could handle it on your own!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Actually... we didn't./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Kris' mom somehow found her way in./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\EA* She can kick SO. MUCH. ASS./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\EA* You should've seen her!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* I guess in a way, she kinda substituted for you./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* You two do look alike... I guess./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\EH* That's great!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\EH* I would love to meet your mom one day, Kris!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\EH* She's probably a very nice lady!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Too nice sometimes.../%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E2* Arright, starting to get tired of this./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E2* Whadya say we get goin', Kris?/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E2* Let's go find the titanic or something!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\EL* What about me?!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Oh, right./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E9* Lancer Fan Club, assemble!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
    c_soundplay(snd_jump)
    c_sel(kr)
    c_jump_sprite(1200, 380, 12, 17, spr_kris_fall_d_dw, spr_kris_dw_landed)
    c_delayfacing(16, "r")
    c_sel(su)
    c_delayfacing(16, "r")
    c_jump_sprite(1130, 380, 12, 17, spr_susie_dw_fall_d, spr_susie_dw_landed)
    c_sel(ra)
    c_delayfacing(16, "r")
    c_jump_sprite(1060, 380, 12, 17, spr_ralsei_jump, spr_teacup_ralsei_land)
    c_wait(20)
    c_soundplay(snd_impact)
    c_wait(16)
    c_soundplay(snd_swing)
    c_sel(kr)
    c_spin(2)
    c_sel(su)
    c_spin(2)
    c_sel(ra)
    c_spin(2)
    c_wait(16)
    c_soundplay(snd_bell)
    c_sel(kr)
    c_sprite(spr_kris_pose)
    c_addxy(-2, -2)
    c_spin(0)
    c_sel(su)
    c_sprite(spr_susie_pose)
    c_addxy(2, 2)
    c_spin(0)
    c_sel(ra)
    c_sprite(spr_ralsei_pose)
    c_addxy(-10, 0)
    c_spin(0)
    c_wait(15)
    c_speaker("susie")
    c_msgsetloc(0, "\\E2* Yeah!/%", "obj_ch2_scene9_slash_Step_0_gml_778_0")
    c_talk_wait()
    c_sel(ra)
    c_addxy(10, 0)
    c_sel(kr)
    c_addxy(2, 2)
    c_sel(su)
    c_addxy(-2, -2)
    c_pannable(false)
    c_actortokris()
    c_actortocaterpillar()
	c_terminatekillactors()
		scr_getchar(3)
    global.cinstance[1] = scr_makecaterpillar(540, 180, 3, 1)
			c_facing("r")

}
if (con == 2)
{
    if (!instance_exists(obj_cutscene_master))
    {
        con = 3
        global.interact = 0
    }
}
