if (con == 0 && obj_mainchara.x >= x && global.interact == 0)
{
    con = 1
    global.interact = 1
}
if (con == 1)
{
con = 2
cutscene_master = scr_cutscene_make()
scr_maincharacters_actors()
scr_cutscene_loaded()
jo = 2
    jo_actor = instance_create(960, 375, obj_actor)
    scr_actor_setup(jo, jo_actor, "jockington")
	c_sel(jo)
	jo_actor.sprite_index = spr_jock_darkworld
	c_sel(jo)
	c_sprite(spr_jock_dead)

ra = 3
    ra_actor = instance_create(1079, 640, obj_actor)
    scr_actor_setup(ra, ra_actor, "ralsei")
	c_sel(ra)
	ra_actor.sprite_index = spr_ralsei_walk_right
	c_sel(ra)
c_shake()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Kris, what the hell was that?!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_sel(su)
c_walk("r", 3, 100)
c_pannable(true)
c_pan_wait(425, 150, 80)
c_sel(jo)
c_speaker("jockington")
c_msgsetloc(0, "\\E4* Ugh..../%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E6* Jockington?!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_sel(jo)
c_speaker("jockington")
c_msgsetloc(0, "\\E1* Kris, Susie, Third Person!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\E0* How'd you get here?/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E1* You know, I was going swimming!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E1* I decided, to swim out far though.../%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E1* I came across this AWESOME house on the docks and,/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E0* I wound up, here, somehow.../%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* You probably passed out./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* You're dreaming./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E0* ...Am I?/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E4* Yeah. Also, you should probably get up./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E4* You've been eating dirt for awhile now./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E7* Susie you know, Jockington always goes up with STYLE!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_sel(jo)
c_wait(120)
c_sel(jo)
c_sprite(spr_jock_darkworld)
c_speaker("susie")
c_msgsetloc(0, "\\E0* Wow./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\E0* You can tag along if you want, Jockington!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Wait, what about battling?/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E2* Battles?!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Yeah./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* We run into some enemies sometimes./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Only three people can fight at a time, though./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Makes it easier for us./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\E0* I'll sit back for now! Battling isn't really my thing anyways./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\E2* I also think that you and Susie are getting better at sparing enemies!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_speaker("rlsei")
c_msgsetloc(0, "\\EEH* Also hi, i'm Ralsei!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E7* Thanks, Ralsei!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("jockington")
c_msgsetloc(0, "\\E0* So, what now?/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Hold on, I got this./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* Follow our lead./%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\E0* 3... 2... 1.../%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("ralsei")
c_msgsetloc(0, "\\EH* Lancer Fan Club, Assemble!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
c_speaker("susie")
c_msgsetloc(0, "\\EH* Hey!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
c_talk_wait()
    c_soundplay(snd_jump)
    c_sel(kr)
    c_jump_sprite(967, 380, 12, 17, spr_kris_fall_d_dw, spr_kris_dw_landed)
    c_delayfacing(16, "r")
    c_sel(jo)
    c_delayfacing(16, "r")
    c_jump_sprite(897, 380, 12, 17, spr_jock_darkworld, spr_jock_land)
    c_sel(ra)
    c_delayfacing(16, "r")
    c_jump_sprite(827, 380, 12, 17, spr_ralsei_jump, spr_teacup_ralsei_land)
    c_wait(20)
    c_soundplay(snd_impact)
    c_wait(16)
    c_soundplay(snd_swing)
    c_sel(kr)
    c_spin(2)
    c_sel(jo)
    c_spin(2)
    c_sel(ra)
    c_spin(2)
    c_wait(16)
    c_soundplay(snd_bell)
    c_sel(kr)
    c_sprite(spr_kris_pose)
    c_addxy(-2, -2)
    c_spin(0)
    c_sel(jo)
    c_sprite(spr_susie_pose)
    c_addxy(2, 2)
    c_spin(0)
    c_sel(ra)
    c_sprite(spr_ralsei_pose)
    c_addxy(-10, 0)
    c_spin(0)
    c_wait(15)
    c_speaker("jockington")
    c_msgsetloc(0, "\\E2* Awesome!/%", "obj_ch2_scene9_slash_Step_0_gml_778_0")
    c_talk_wait()
    c_sel(ra)
    c_addxy(10, 0)
    c_sel(kr)
    c_addxy(2, 2)
    c_sel(jo)
    c_addxy(-2, -2)
    c_speaker("susie")
	c_msgsetloc(0, "\\EH* Ralsei!/%", "obj_example_cutscene_slash_Step_0_gml_60_0")
	c_talk_wait()
	c_pannable(false)
	c_actortokris()
    c_actortocaterpillar()
	c_terminatekillactors()
    c_actortokris()
    c_actortocaterpillar()
	c_terminatekillactors()
	global.cinstance[1] = scr_makecaterpillar(540, 180, 2, 0)
	global.cinstance[1] = scr_makecaterpillar(540, 180, 9, 1)
	global.cinstance[1] = scr_makecaterpillar(540, 180, 3, 2)
}
if (con == 2)
{
    if (!instance_exists(obj_cutscene_master))
    {
        con = 3
        global.interact = 0
    }
}
